name: external/scripts/prepare.sh

on:
  push:
    branches:
      - main
jobs:
  windows-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "mavka-ukr-static/mavka-windows-x86_64"
          path: "build/windows-x86_64"
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY_MAVKA_WINDOWS }}
          persist-credentials: true
          fetch-depth: 1
      - run: |
          export MAVKA_VERSION="$(cat Версія)"
          export GIT_LATEST_COMMIT_HASH="$(git rev-parse --short HEAD)"
          wget https://github.com/tsil-ukr/files/raw/main/випуски-цілі/0.38.0/ціль-0.38.0-linux-x86_64.tar.gz
          tar -xvzf ціль-0.38.0-linux-x86_64.tar.gz
          cp -a build/windows-x86_64/.git .git-build-windows-x86_64
          rm -rf build/windows-x86_64
          mkdir -p build/windows-x86_64
          cp -a .git-build-windows-x86_64/ build/windows-x86_64/.git
          rm -rf .git-build-windows-x86_64/
          TSIL=ціль-0.38.0-linux-x86_64/bin/ціль sh external/scripts/prepare.sh windows-x86_64
          cp Версія build/windows-x86_64
          cd build/windows-x86_64
          statusResult=$(git status -u --porcelain)
          if [ -z "$statusResult" ]
          then
            exit 0
          fi
          git config --local user.name "kohutd"
          git config --local user.email "davyd.kohut@gmail.com"
          git add .
          git commit -m "$MAVKA_VERSION-$GIT_LATEST_COMMIT_HASH"
          git tag "$MAVKA_VERSION-$GIT_LATEST_COMMIT_HASH"
          cd -
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          tags: true
          directory: "build/windows-x86_64"
          repository: "mavka-ukr-static/mavka-windows-x86_64"
          ssh: true
          github_token: ${{ secrets.SSH_DEPLOY_KEY_MAVKA_WINDOWS }}
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "mavka-ukr-static/mavka-linux-x86_64"
          path: "build/linux-x86_64"
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY_MAVKA_LINUX_X86_64 }}
          persist-credentials: true
          fetch-depth: 1
      - run: |
          export MAVKA_VERSION="$(cat Версія)"
          export GIT_LATEST_COMMIT_HASH="$(git rev-parse --short HEAD)"
          wget https://github.com/tsil-ukr/files/raw/main/випуски-цілі/0.38.0/ціль-0.38.0-linux-x86_64.tar.gz
          tar -xvzf ціль-0.38.0-linux-x86_64.tar.gz
          cp -a build/linux-x86_64/.git .git-build-linux-x86_64
          rm -rf build/linux-x86_64
          mkdir -p build/linux-x86_64
          cp -a .git-build-linux-x86_64/ build/linux-x86_64/.git
          rm -rf .git-build-linux-x86_64/
          TSIL=ціль-0.38.0-linux-x86_64/bin/ціль sh external/scripts/prepare.sh linux-x86_64
          cp Версія build/linux-x86_64
          cd build/linux-x86_64
          statusResult=$(git status -u --porcelain)
          if [ -z "$statusResult" ]
          then
            exit 0
          fi
          git config --local user.name "kohutd"
          git config --local user.email "davyd.kohut@gmail.com"
          git add .
          git commit -m "$MAVKA_VERSION-$GIT_LATEST_COMMIT_HASH"
          git tag "$MAVKA_VERSION-$GIT_LATEST_COMMIT_HASH"
          cd -
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          tags: true
          directory: "build/linux-x86_64"
          repository: "mavka-ukr-static/mavka-linux-x86_64"
          ssh: true
          github_token: ${{ secrets.SSH_DEPLOY_KEY_MAVKA_LINUX_X86_64 }}